In [1]:
import tensorflow as tf
from tensorflow.keras.layers import Input, Dense, Conv2D, MaxPooling2D, Flatten, Dropout
from keras.models import Sequential, Model

In [3]:
model_cnn = Sequential([
    Conv2D(64, 3, input_shape=(128,128,1), use_bias=True, ),
    MaxPooling2D(pool_size=4),
    Flatten(),
    Dropout(0.5),
    Dense(1, activation='softmax')
])

In [4]:
model_cnn.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d_1 (Conv2D)                    │ (None, 126, 126, 64)        │             640 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_1 (MaxPooling2D)       │ (None, 31, 31, 64)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten_1 (Flatten)                  │ (None, 61504)               │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_1 (Dropout)                  │ (None, 61504)               │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                   │          61,505 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 62,145 (242.75 KB)

 Trainable params: 62,145 (242.75 KB)

 Non-trainable params: 0 (0.00 B)

In [5]:
model_cnn.save('simple_cnn.h5')

In [6]:
input_shape = (4, 28, 28, 3)

In [7]:
x = tf.random.normal(input_shape)

In [8]:
x.shape

TensorShape([4, 28, 28, 3])

In [9]:
input_shape[1:]

(28, 28, 3)

In [10]:
y = Conv2D(2, 2, activation='relu', input_shape=input_shape[1:])(x)
#y = Conv2D(2, 3, activation='relu', input_shape=input_shape[1:])(x)
#y = Conv2D(2, 4, activation='relu', input_shape=input_shape[1:])(x)
#y = Conv2D(2, [3,2], activation='relu', input_shape=input_shape[1:])(x)


In [11]:
y.shape

TensorShape([4, 27, 27, 2])

In [12]:
y[0].shape

TensorShape([27, 27, 2])

In [13]:
z = MaxPooling2D(pool_size=3, strides=3)(y)

In [14]:
z.shape

TensorShape([4, 9, 9, 2])

In [15]:
z[0].shape

TensorShape([9, 9, 2])

In [16]:
ab = Flatten()(z)

In [17]:
ab.shape

TensorShape([4, 162])

In [18]:
ab[0].shape

TensorShape([162])

In [19]:
abz = Dropout(0.5,  noise_shape=None, seed=10)(ab)

In [20]:
abz.shape

TensorShape([4, 162])

In [21]:
abz[0]

<tf.Tensor: shape=(162,), dtype=float32, numpy=
array([1.4975202 , 2.2460663 , 2.068832  , 1.1108522 , 2.146647  ,
       0.7562423 , 1.7535814 , 1.7017889 , 2.2866676 , 0.8738275 ,
       1.0932899 , 2.685424  , 1.6882848 , 1.0964241 , 1.0484043 ,
       0.9370376 , 1.3411849 , 0.9352224 , 2.3294833 , 1.6116383 ,
       1.9972193 , 0.51553494, 1.0983983 , 1.6466842 , 1.155233  ,
       1.5289662 , 1.8781133 , 0.809777  , 1.6155486 , 1.4915042 ,
       2.7111068 , 1.2171519 , 3.2441564 , 1.0271186 , 1.9115641 ,
       1.5433967 , 1.1570873 , 0.84880996, 1.4964309 , 1.7392683 ,
       1.5466511 , 1.5290321 , 2.4921567 , 1.7994876 , 1.3859011 ,
       0.550746  , 1.5592884 , 0.5769222 , 1.1621573 , 0.8895919 ,
       3.1457853 , 2.9612868 , 1.0676527 , 1.6059518 , 0.8619251 ,
       2.1442199 , 2.421272  , 2.4089484 , 2.6084456 , 1.3563275 ,
       1.5116154 , 1.3219273 , 1.42456   , 0.4944952 , 0.53157043,
       2.4445271 , 1.5312268 , 1.3460697 , 1.2529498 , 1.1308441 ,
       1.29801

In [22]:
final = Dense(10, activation='softmax')(abz)

In [23]:
final

<tf.Tensor: shape=(4, 10), dtype=float32, numpy=
array([[7.8575913e-04, 4.4075344e-04, 1.0256187e-01, 4.9626686e-02,
        2.5178581e-03, 2.7509263e-02, 3.0511909e-04, 3.3111949e-02,
        6.8862280e-03, 7.7625453e-01],
       [7.6278388e-03, 5.8188047e-03, 3.4531578e-01, 2.1793991e-02,
        9.7102141e-03, 1.0194173e-02, 7.1322144e-04, 3.3464527e-01,
        1.8737739e-02, 2.4544293e-01],
       [1.0217120e-03, 1.4026726e-03, 2.5279546e-01, 8.0124848e-02,
        5.5803480e-03, 3.0257652e-02, 2.1934628e-03, 1.7252007e-01,
        3.4571127e-03, 4.5064661e-01],
       [1.1768392e-03, 4.1635367e-03, 1.0725942e-01, 2.2918537e-02,
        5.5581313e-02, 7.1615942e-02, 6.3133300e-03, 1.4810477e-01,
        4.7442093e-03, 5.7812208e-01]], dtype=float32)>

In [24]:
final_relu = Dense(10, activation='relu')(abz)

In [25]:
final_relu

<tf.Tensor: shape=(4, 10), dtype=float32, numpy=
array([[5.2680554 , 0.6666809 , 0.        , 5.785929  , 0.        ,
        4.2804623 , 0.        , 0.8665559 , 2.39625   , 0.        ],
       [4.459279  , 0.        , 0.        , 4.265618  , 0.        ,
        2.7767386 , 0.28385615, 0.        , 1.5186286 , 0.        ],
       [3.3813488 , 0.6856073 , 0.        , 5.639885  , 0.        ,
        4.2465253 , 0.07171637, 2.0491588 , 1.0050831 , 0.        ],
       [4.820467  , 0.        , 0.        , 7.1611485 , 0.75623137,
        5.271007  , 0.29216692, 0.46482095, 2.6835186 , 0.        ]],
      dtype=float32)>